### ISSUE TITLE
Read from {mdl}.json file instead of yaml in create package

### ISSUE THREAD

**Issue by chrispcampbell** [climateinteractive/SDEverywhere#357]
I found this code and comment in the `create` package in `step-config.ts`:

```ts
  // Read `build/{mdl}_vars.yaml`
  // TODO: For now the printVarList code only outputs txt and yaml files; we'll use the
  // yaml file for now, but that means we have a dependency on the `yaml` package.  Once
  // we change the `compile` package to output JSON, we'll need to change this code.
  const varsYamlFile = joinPath(buildDir, `${mdlName}_vars.yaml`)
  const varsYamlContent = await readFile(varsYamlFile, 'utf8')
  const varObjs = yaml.parse(varsYamlContent)
```

We are about to have the JSON file available as an alternative to the YAML one (see #105).  Once those changes land, we can update the above code to read from `{mdl}.json`, and we can drop the `yaml` package dependency.

**Comment by chrispcampbell** [comment]
For the record, there was a related discussion thread (see #613) that showed that the `create` package can report an error when parsing a large YAML file, see stack trace below (copied from that thread):

```
ReferenceError: Excessive alias count indicates a resource exhaustion attack
    at Alias.toJSON (/home/sarribol/.npm/_npx/7c716b646d7d555a/node_modules/yaml/dist/nodes/Alias.js:61:23)
    at Object.toJS (/home/sarribol/.npm/_npx/7c716b646d7d555a/node_modules/yaml/dist/nodes/toJS.js:22:26)
    at Object.addPairToJSMap (/home/sarribol/.npm/_npx/7c716b646d7d555a/node_modules/yaml/dist/nodes/addPairToJSMap.js:25:34)
    at YAMLMap.toJSON (/home/sarribol/.npm/_npx/7c716b646d7d555a/node_modules/yaml/dist/nodes/YAMLMap.js:124:28)
    at Object.toJS (/home/sarribol/.npm/_npx/7c716b646d7d555a/node_modules/yaml/dist/nodes/toJS.js:22:26)
    at YAMLSeq.toJSON (/home/sarribol/.npm/_npx/7c716b646d7d555a/node_modules/yaml/dist/nodes/YAMLSeq.js:76:27)
    at Object.toJS (/home/sarribol/.npm/_npx/7c716b646d7d555a/node_modules/yaml/dist/nodes/toJS.js:22:26)
    at Document.toJS (/home/sarribol/.npm/_npx/7c716b646d7d555a/node_modules/yaml/dist/doc/Document.js:302:26)
    at Object.parse (/home/sarribol/.npm/_npx/7c716b646d7d555a/node_modules/yaml/dist/public-api.js:78:16)
    at readModelVars (file:///home/sarribol/.npm/_npx/7c716b646d7d555a/node_modules/@sdeverywhere/create/dist/index.js:393:24)
```

Since we were planning to remove the YAML reading code and `yaml` package dependency as part of this issue anyway, we should proceed with that change (to read from the JSON file instead), which should resolve the error reported above.
