### ISSUE TITLE
Model reader running out of stack with a large model

### ISSUE THREAD

**Issue by ToddFincannonEI** [climateinteractive/SDEverywhere#442]
The latest EPS model is much larger than previous versions. The SDEverywhere code gen command often crashes after running out of stack.

```
Generating the C model...
RangeError: Maximum call stack size exceeded
    at node_modules/.pnpm/ramda@0.27.2/node_modules/ramda/src/internal/_curry3.js:38:31
    at f1 (node_modules/.pnpm/ramda@0.27.2/node_modules/ramda/src/internal/_curry1.js:19:17)
    at find (node_modules/.pnpm/ramda@0.27.2/node_modules/ramda/src/find.js:47:9)
    at node_modules/.pnpm/ramda@0.27.2/node_modules/ramda/src/internal/_dispatchable.js:50:15
    at Module.f2 (node_modules/.pnpm/ramda@0.27.2/node_modules/ramda/src/internal/_curry2.js:34:14)
    at findVarWithRefId (packages/compile/src/model/model.js:652:19)
    at varWithRefId (packages/compile/src/model/model.js:664:16)
    at recordRefsOfVariable (packages/compile/src/model/model.js:452:24)
    at recordRefsOfVariable (packages/compile/src/model/model.js:455:11)
    at recordRefsOfVariable (packages/compile/src/model/model.js:455:11)
```

**Comment by ToddFincannonEI** [comment]
I found that the call stack for the recursive `recordRefsOfVariable` function was getting over 5000 calls deep on the latest EPS model. This function is tail recursive, and can be refactored to use iteration instead.

I tried working around this by simply using the Node `--stack-size` argument. This sometimes helped, but not always. Node 20 did better than Node 18. Finally, nothing worked, so I decided to refactor `recordRefsOfVariable`.

I added an auxiliary `refStack` array to hold refIds encountered as the dependency tree is walked, in lieu of the recursive call stack. When entering the function with an initial var, its references are first pushed on the stack. Then `refStack` is processed by popping a var and handling it as before, but pushing its references onto `refStack` insteading of doing the recursive call.

I tried two implementations of the `pushRefs` function that adds a var's reference to the stack. Using the spread operator instead of `concat` as in the original code delivered 14% faster overall runtime for the entire build process.

Upon reviewing the code, I also decided to change `referencedVarNames` from an array to a Set to increase performance.
